config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  resources :recipes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  
  before_save { self.email = email.downcase }
  
  validates :chefname, presence: true, length: { maximum: 30 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
             format: {with: VALID_EMAIL_REGEX},
             uniqueness: { case_sensitive: false }
             
  has_many :recipes
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
   validates :name, presence: true
   validates :description, presence: true, length: { minimum: 5, maximum: 500 }
   
   belongs_to :chef
   validates :chef_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def new
    @recipe = Recipe.new
  end
  
  
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.first
    if @recipe.save
      flash[:success] = "Recipe was created successfully"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
       # handle this
       flash[:success] = "Recipe was updated successfully"
       redirect_to recipe_path(@recipe)
    else
        render 'edit'
    end
  end
  
  
private

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname, class: "img-circle")
  end
  
end

app/views/layouts/_footer.html.erb
    
    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <span class="text-muted">Place footer content here.
        <%= link_to "about", "#" %>
        </span>
      
      </div>
    </footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= msg %>
      </div>
    <% end %>
  </div>
  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Myrecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    
    <div class="container">
    <%= yield %>
    </div>
    
    <br>
    <br>
    
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
   <h1>Welcome to MyRecipes</h1>
   <h2>The best recipe sharing app!</h2>
   <p><%= link_to "Sign up or Log in", "#", class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
      

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<% if @recipe.errors.any? %>

   <div class="row">
     <div class="col-md-8 col-md-offset-2">
       <div class="panel panel-danger">
          <div class="panel-heading">
              <h2 class="panel-title">
              <%= pluralize(@recipe.errors.count, "error") %>
              prohibted this <%= @recipe.class %> from being saved:
              </h2>
              
              <div class="panel-body">
                <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
                </ul>
                </div>
              </div>
           </div>
          </div>
    </div>
<% end %>


<div class="row">
  <div class = "col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       <div class="form-group">
           <div class="control-label col-md-2">
             <%= f.label :name %>
           </div>
           <div class="col-md-8">
             <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
           </div>
       </div>

       <div class="form-group">
           <div class="control-label col-md-2">
               <%= f.label :description %>
           </div>
           <div class="col-md-8">
               <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
           </div>
       </div> 
       
       <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
           <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
         </div>
       </div>
       
   <% end %>
    
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
    
  </div>  
</div>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>
  
  <div class="col-md-8 well">
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    
    <p><%= truncate(recipe.description, length: 150) %></p>
    <p>
      <span class="quiet">
      <small>Created <%= time_ago_in_words(recipe.created_at) %> ago</small>
      </span>
    </p>
  </div>
  
  </div>
  
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>

<% if @recipe.errors.any? %>

   <div class="row">
     <div class="col-md-8 col-md-offset-2">
       <div class="panel panel-danger">
          <div class="panel-heading">
              <h2 class="panel-title">
              <%= pluralize(@recipe.errors.count, "error") %>
              prohibted this <%= @recipe.class %> from being saved:
              </h2>
              
              <div class="panel-body">
                <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
                </ul>
                </div>
              </div>
           </div>
          </div>
    </div>
<% end %>


<div class="row">
  <div class = "col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
       <div class="form-group">
           <div class="control-label col-md-2">
             <%= f.label :name %>
           </div>
           <div class="col-md-8">
             <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
           </div>
       </div>

       <div class="form-group">
           <div class="control-label col-md-2">
               <%= f.label :description %>
           </div>
           <div class="col-md-8">
               <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
           </div>
       </div> 
       
       <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
           <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
         </div>
       </div>
       
   <% end %>
    
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
    
  </div>  
</div>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr/>
  
  <%= simple_format(@recipe.description) %>
  <hr/>
  
  <div class="pull-right">
    <p class="center">
    <em>Created by:</em> 
    </p>
    <p class="center">
      <%= link_to gravatar_for(@recipe.chef), recipes_path %>
    </p>
    <p class="center">
      <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="pull-right">
        <%= time_ago_in_words(@recipe.created_at) %> ago
      </div>
    </p>
  </div>
  
</div>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr/>